import Card from 'components/common/Card';
import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';

import content from '../content/meta.json';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  const { data: session }: any = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>DApp test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.collectionContainer}>
          {content.map((nft) => {
            return (
              <Card
                marginTop={30}
                name={nft.name}
                image={nft.image}
                category={nft.category}
                description={nft.description}
                price={nft.attributes[2].value}
              />
            );
          })}
        </div>

        {session && (
          <>
            Signed in as {session?.user.email} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}
        {!session && (
          <>
            Not signed in <br />
            <button onClick={() => signIn('github')}>Sign in with github</button>
            <button onClick={() => signIn('facebook')}>Sign in with facebook</button>
            <button onClick={() => signIn('google')}>Sign in with google</button>
          </>
        )}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
